### ISSUE TITLE
Code completion for properties show the type as the property name

### ISSUE THREAD

**Issue by eskatos** [gradle/declarative-vscode-extension#2]
![declarative-vscode-property-completion-bug](https://github.com/user-attachments/assets/d202f723-f09d-4a3a-bb56-4dc2ef7d2159)

It should show the property name instead.

**Comment by hegyibalint** [comment]
Fixed by https://github.com/gradle/declarative-lsp/commit/caff8a1f93ff47eedb478009c1409178db0c5354
